### ISSUE TITLE
页面访问缓慢的

### ISSUE THREAD

**Issue by adrianyao89** [b3log/index#4]
![image](https://cloud.githubusercontent.com/assets/3348475/18500991/9266747e-7a7f-11e6-99c1-d636573cd34f.png)

![image](https://cloud.githubusercontent.com/assets/3348475/18501027/e13a3fc2-7a7f-11e6-8e72-0c960ea3f302.png)

最近发现由于这个地址的访问失败，会导致整个页面加载非常的慢，在此页面加载1.2分钟失败后，页面才能加载出来，希望能够给予解决方法。

**Comment by Vanessa219** [comment]
已移除 fonts
